### ISSUE TITLE
Errors don't surface when starting a consumer fails to authenticate

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#104]
The cluster I'm testing is having random authentication issues (wink wink @wtrocki). Starting a consumer shows me the consumer started page, but in the console, I can see errors like:
```
stack trace: KafkaJSSASLAuthenticationError: SASL PLAIN authentication failed: Authentication failed: credentials for user could not be verified
	at PlainAuthenticator.authenticate (/Users/fbricon/Dev/projects/vscode-kafka/dist/extension.js:130763:21)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async SASLAuthenticator.authenticate (/Users/fbricon/Dev/projects/vscode-kafka/dist/extension.js:130654:5)
	at async Broker.connect (/Users/fbricon/Dev/projects/vscode-kafka/dist/extension.js:129736:9)
	at async /Users/fbricon/Dev/projects/vscode-kafka/dist/extension.js:131248:9
	at async Cluster.connect (/Users/fbricon/Dev/projects/vscode-kafka/dist/extension.js:131713:5)
	at async Object.connect (/Users/fbricon/Dev/projects/vscode-kafka/dist/extension.js:133447:5)
```

Obviously produced messages (that works fine) are not received by the consumer.

Anyways, the point is, those authentication errors should be seen by the user

**Comment by angelozerr** [comment]
I think https://github.com/jlandersen/vscode-kafka/issues/22 should cover this issue.
