### ISSUE TITLE
Error in consumer: Snappy compression not implemented

### ISSUE THREAD

**Issue by tejasvichudasma-zefr** [jlandersen/vscode-kafka#217]
Getting this error when trying read from topic

[2021-12-27 14:16:04.802] [renderer9] [error] [Extension Host] {"level":"ERROR","timestamp":"2021-12-27T22:16:05.020Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNotImplemented: Snappy compression not implemented","groupId":"vscode-dmds-inventory-search_definition","stack":"KafkaJSNotImplemented: Snappy compression not implemented\n\tat 2 (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1914612)\n\tat lookupCodecByAttributes (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1914894)\n\tat e.exports (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1922596)\n\tat e.exports (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1960314)\n\tat s (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1965003)\n\tat e.readArrayAsync (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1897261)\n\tat l (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1965067)\n\tat e.readArrayAsync (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1897261)\n\tat Object.decode (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1965257)\n\tat e.exports.send (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1868930)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async e.exports.[private:Broker:sendRequest] (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1799844)\n\tat async e.exports.fetch (/home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1794638)\n\tat async /home/ec2-user/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.14.0/dist/extension.js:2:1830184"}

**Comment by angelozerr** [comment]
By searching quickly it seems we should do (where?) https://github.com/tulios/kafkajs-snappy#configuration to support snappy.

**Comment by TomasEkeli** [comment]
i am getting a very similar error with lz4 compression defined by the producer

```
"level":"ERROR","timestamp":"2022-07-07T10:31:14.419Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNotImplemented: LZ4 compression not implemented","groupId":"tomas-tests-consumption-from-vscode2","stack":"KafkaJSNotImplemented: LZ4 compression not implemented\n    at 3 (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1923520)\n    at lookupCodecByAttributes (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1923738)\n    at e.exports (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1931557)\n    at e.exports (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1969586)\n    at s (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1968253)\n    at e.readArrayAsync (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1904983)\n    at l (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1968317)\n    at e.readArrayAsync (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1904983)\n    at Object.decode (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1968507)\n    at e.exports.send (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1874541)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at e.exports.[private:Broker:sendRequest] (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1800982)\n    at e.exports.fetch (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1796062)\n    at e.exports.fetch (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1831225)\n    at e.exports.fetch (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1854597)\n    at Object.start (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1837029)\n    at async Promise.all (index 0)\n    at Object.start (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1836325)\n    at e.exports.scheduleFetchManager (/root/.vscode-server/extensions/jeppeandersen.vscode-kafka-0.15.0/dist/extension.js:2:1851568)
```

i think the compression should be part of the message (according to https://github.com/tulios/kafkajs/issues/1141#issuecomment-872104648) - maybe that's not working in this extension?
